import "@/styles/globals.css";
import vazirFont from "@/constants/localFont";

// import { Toaster } from "react-hot-toast";
// import AuthProvier from "@/context/AuthContext";
// import ReactQueryProvider from "@/providers/ReactQueryProvider";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "بلاگینو – فضای خلاقانه برای افکار شما",
  description:
    "بلاگینو یک اپلیکیشن وبلاگ ساده و مدرن است که به کاربران این امکان را می‌دهد تا ایده‌ها، داستان‌ها و نظرات خود را به راحتی و خلاقانه به اشتراک بگذارند. با طراحی مینیمالیستی و رابط کاربری شهودی، بلاگینو تجربه‌ای بی‌نظیر برای نویسندگان و خوانندگان فراهم می‌کند. به جامعه‌ای از سازندگان محتوا بپیوندید و صدای خود را با جهان به اشتراک بگذارید.",
  keywords:
    "بلاگینو، اپلیکیشن وبلاگ، پلتفرم نوشتن، نوشتن خلاقانه، وبلاگ فارسی، اشتراک‌گذاری ایده‌ها، تولید محتوا، نویسندگی آنلاین",
  author: "تیم بلاگینو",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="dark-mode">
      <body className={`min-h-screen  ${vazirFont.variable} font-sans `}>
        {children}
        {/* <Toaster /> */}
        {/* <ReactQueryProvider> */}
        {/* <AuthProvier>{children}</AuthProvier> */}
        {/* </ReactQueryProvider> */}
      </body>
    </html>
  );
}
